name: Build ROM

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target (e.g. matrixx_sky)'
        required: true
      variant:
        description: 'Build variant (user, userdebug, eng)'
        default: 'userdebug'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential openjdk-11-jdk git-core gnupg flex bison gperf curl git git-lfs repo
      
      - name: Setup Matrixx Source and Local Manifest
        run: |
          # गिटहब के छिपे हुए टोकन को डिलीट करना
          git config --global --unset-all http.https://github.com || true
          
          git config --global user.name "Ram999000"
          git config --global user.email "ram@example.com"
          
          # 1. गिटलैब के एक्टिव और पब्लिक रिपोजिटरी पाथ से डायरेक्ट क्लोन करना
          mkdir -p .repo/manifests
          git clone https://gitlab.com .repo/manifests -b 15.0
          ln -sf .repo/manifests/default.xml .repo/manifest.xml
          
          # 2. आपका लोकल मैनिफ़ेस्ट डाउनलोड करना
          mkdir -p .repo/local_manifests
          curl -L -o .repo/local_manifests/matrixx.xml https://githubusercontent.com
          
          # 3. सोर्स कोड सुरक्षित सिंक करना
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build ROM
        run: |
          chmod +x build.sh
          ./build.sh "${{ github.event.inputs.target }}" "${{ github.event.inputs.variant }}"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rom-${{ github.event.inputs.target }}
          path: 'out/target/product/**/*.zip'
          retention-days: 7
